// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-04-15 05:42:51.8037 -0300 -03 m=+1.136912967

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Danilo Pantani",
            "url": "https://github.com/Pantani"
        },
        "license": {
            "name": "MIT License",
            "url": "https://raw.githubusercontent.com/trustwallet/redemption/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/annotate": {
            "post": {
                "description": "Get all annotates html snippet",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "annotate"
                ],
                "summary": "Get Annotate",
                "operationId": "get_annotate",
                "parameters": [
                    {
                        "description": "The html to be replaced",
                        "name": "html",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/replacer.Html"
                        }
                    }
                }
            }
        },
        "/names": {
            "get": {
                "description": "Get all names details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "name"
                ],
                "summary": "Get all names",
                "operationId": "get_all_names",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/replacer.Status"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete all name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "name"
                ],
                "summary": "Delete all names",
                "operationId": "del_all_names",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/replacer.Status"
                        }
                    }
                }
            }
        },
        "/names/{name}": {
            "get": {
                "description": "Get a name detail",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "name"
                ],
                "summary": "Get name",
                "operationId": "get_name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/replacer.Status"
                        }
                    }
                }
            },
            "put": {
                "description": "Insert or update a name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "name"
                ],
                "summary": "Insert name",
                "operationId": "insert_name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "The url to insert",
                        "name": "url",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/replacer.NameRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/replacer.Status"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "name"
                ],
                "summary": "Delete name",
                "operationId": "del_name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "the name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/replacer.Status"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Get application status",
                "tags": [
                    "status"
                ],
                "summary": "Get Status",
                "operationId": "health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/replacer.Status"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "replacer.Html": {
            "type": "string"
        },
        "replacer.NameRequest": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "replacer.Status": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "Backend Interview",
	Description: "Replacer API for test interview.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
